 
import type { Metadata } from "next"; 

import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
 
// import favlogo from '../public/logo-fav.svg'

 
export const metadata: Metadata = {
  title: "Joshadi",
  description: "Generated by create next app",
  icons: {
    icon: "../logo-fav.svg",
  },

 
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      {/* <link rel="icon" href="../logo-fav.svg" /> */}
        
      <body
        className={`antialiased`}
      >
        <AuthProvider>

        {children}
        </AuthProvider>
      </body>
       
    </html>
   
  );
}
